spring:
  redis:
    port:  # redis server port
    host:  # redis server host
    lettuce:
      pool:
        max-active: 50
        max-wait: 2000
        max-idle: 20
        min-idle: 5
#    cluster:
#      nodes:
#        - 114.67.168.57:31010
#        - 114.67.168.57:31011
#        - 114.67.168.57:31012
#    lettuce:
#      pool:
#        max-active: 50
#        max-wait: 2000
#        max-idle: 20
#        min-idle: 5
  application:
    name: aaaaaaaaaa
multiple-cache:
  redis:
    - name: testCache
      expire: 100
#  caffeine:
#    - name: testCache
#      expireAfterAccess: 30
#      initialCapacity: 100
#      maximumSize: 1000
#  multiple:
#    - name: testCache
#      caffeine:
#        expireAfterAccess: 30
#        initialCapacity: 100
#        maximumSize: 1000
#      redis:
#        expire: 100

logging:
  level:
    com:
      zy:
        github:
          multiple:
            cache:
              sync: debug


